#环境
spring:
  profiles:
    active: dev
server:
  port: 8081
#pagehelper分页配置 第二种和第三种不需要 重点讲的第一种需要
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
mybatis:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
